name: PluginPortal
version: 2.0.0
main: link.portalbox.pluginportal.PluginPortal
api-version: 1.13
authors: [ Portal Box Team ]
description: In-game plugin downloader and updater using the SpigotMC marketplace.
website: https://pluginportal.link
libraries:
  - commons-io:commons-io:2.11.0
  - com.google.code.gson:gson:2.10.1
  - com.fasterxml.jackson.core:jackson-core:2.15.1
  - com.fasterxml.jackson.core:jackson-databind:2.15.1
  - com.fasterxml.jackson.module:jackson-module-kotlin:2.15.1
commands:
  pluginportal:
    aliases: [pp]
    description: Plugin Portal command.