name: Nightly Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      # Make the Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Run release task
      - name: Run release task
        run: ./gradlew publishNightlyPublicationToHangar -Pio.papermc.hangar-publish-plugin.default-api-key=${{ secrets.HANGAR_API_KEY }
